In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.20.1


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 3 == 1]

array([1, 4, 7])

In [6]:
arr[arr % 3 == 1] = -1
arr

array([ 0, -1,  2,  3, -1,  5,  6, -1,  8,  9])

In [14]:
arr = np.arange(10)
arr.reshape(5, -1) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [19]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)
#only a unique elements remain

array([1, 2, 3, 4])

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)
#the index numbers where they match

(array([1, 3, 5, 7], dtype=int64),)

In [21]:
a = np.arange(15)

#we use where command
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange(9).reshape(3,3)
arr


arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [23]:
arr = np.arange(9).reshape(3,3)

#reverse
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [26]:
arr = np.arange(9).reshape(3,3)
rand_num = np.random.uniform(1,10, size=(4,3))
print(rand_num)

[[2.00413358 6.8889591  9.14892926]
 [5.125336   6.71552924 6.03027182]
 [4.42365448 8.03229967 2.36869763]
 [8.04332174 8.99178456 4.93461291]]


In [28]:
rand_arr = np.random.random([5,3])

#we set prescion to 3 dec
np.set_printoptions(precision=3)
rand_arr[:5]

array([[0.033, 0.817, 0.102],
       [0.722, 0.186, 0.954],
       [0.611, 0.858, 0.761],
       [0.681, 0.654, 0.133],
       [0.778, 0.079, 0.392]])

In [40]:
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)
#only 6 element shown

[ 0  1  2 ... 12 13 14]


In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [44]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [47]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)
#now they are between o and 1

[0.222 0.167 0.111 ... 0.611 0.528 0.444]


In [48]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [52]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [54]:
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

In [61]:
np.isnan(iris_2d).any()
#to check if any null values in our iris_2d array

False

In [63]:
iris_2d[np.isnan(iris_2d)] = -1
iris_2d[:4]
#since there is no 0 value no -1

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [65]:
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
#formula for calc of volume applied
volume = (np.pi * petallength * (sepallength**2))/3

volume = volume[:, np.newaxis]

# Add the new column
new = np.hstack([iris_2d, volume])

new[:4]

array([[ 5.1  ,  3.5  ,  1.4  ,  0.2  , 38.133],
       [ 4.9  ,  3.   ,  1.4  ,  0.2  , 35.2  ],
       [ 4.7  ,  3.2  ,  1.3  ,  0.2  , 30.072],
       [ 4.6  ,  3.1  ,  1.5  ,  0.2  , 33.238]])

In [70]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [71]:
#most unique value
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [73]:
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]
#first elemtn greater than givenvalue

array([50], dtype=int64)

In [78]:
#top five max values
np.random.seed(100)
a = np.random.uniform(1,20, 20)

# Solution:
#print(a.argsort())
np.argpartition(-a, 5)[:5]

array([15, 10,  3,  7, 18], dtype=int64)

In [83]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


<ipython-input-83-17e505e582f3>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3]).astype('object')


In [84]:
#ranking items in an array
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)


print(a.argsort().argsort())
print('Array: ', a)

Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [91]:
#max in each row of 2d
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
#a

# Solution 1
amax = np.amax(a, axis=1)
print(a)
print('max in each row')
print(amax)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
max in each row
[9 8 6 3 9]


Question 1 Part 2

In [92]:
import pandas as pd
print(pd.__version__)

1.2.4


In [93]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Solution
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [94]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))


df = pd.concat([ser1, ser2], axis=1)
print(df.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


In [95]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [96]:
#items in ser1 but not in ser2
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [98]:
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))


np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.251,  7.71 , 10.923, 13.364, 18.095])

In [99]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))


ser.value_counts()

d    7
e    6
f    4
h    4
b    4
c    2
g    2
a    1
dtype: int64

In [100]:
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: d    7
e    6
f    4
h    4
b    4
c    2
g    2
a    1
dtype: int64


0     Other
1         e
2         d
3         e
4     Other
5     Other
6         d
7     Other
8     Other
9     Other
10    Other
11        d
12        e
13        e
14    Other
15    Other
16    Other
17    Other
18        d
19        e
20        e
21        d
22        d
23        d
24    Other
25    Other
26    Other
27    Other
28    Other
29    Other
dtype: object

In [101]:
ser = pd.Series(np.random.randint(1, 10, 35))


df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  8  8  1  3  4
1  3  6  9  2  1
2  8  7  3  1  9
3  3  6  2  9  2
4  6  5  3  9  4
5  6  1  4  7  4
6  5  8  7  4  1


In [102]:

print(ser)
np.argwhere(ser % 3==0)

0     8
1     8
2     1
3     3
4     4
5     3
6     6
7     9
8     2
9     1
10    8
11    7
12    3
13    1
14    9
15    3
16    6
17    2
18    9
19    2
20    6
21    5
22    3
23    9
24    4
25    6
26    1
27    4
28    7
29    4
30    5
31    8
32    7
33    4
34    1
dtype: int32


ValueError: Length of passed values is 1, index implies 35.

In [103]:
#exctract items at given pos
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     8
4     4
8     2
14    9
20    6
dtype: int32

In [104]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [106]:
#pos of items in series b of ser a
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [107]:
#How to compute the mean squared error on a truth and predicted series?
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)

0.28641865381004566

In [108]:
#convert each to upper case
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.map(lambda x: x[0].upper() + x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [109]:
#num of char in each
ser = pd.Series(['how', 'to', 'kick', 'ass?'])


ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [110]:
#diff btw consec numbers in series
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])


print(ser.diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]


In [111]:
#convert to date and time
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [114]:
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())


Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]


<ipython-input-114-c06c487a35c4>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print("Week number: ", ser_ts.dt.weekofyear.tolist())


In [115]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [116]:
#filter for words woth atleast 2 vowels
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [117]:
#mean grouped by another series
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))


weights.groupby(fruit).mean()

apple     5.666667
banana    7.500000
carrot    4.600000
dtype: float64

In [118]:
#getting ecludoian distance
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5
#simply apply the formula

18.16590212458495

In [119]:
#creating a time series
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    1
2000-01-08    1
2000-01-15    6
2000-01-22    7
2000-01-29    7
2000-02-05    6
2000-02-12    7
2000-02-19    5
2000-02-26    8
2000-03-04    4
Freq: W-SAT, dtype: int32

In [124]:
#fill in for empty values
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').bfill()
ser.resample('D').bfill().ffill() 


2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [125]:
#importing only specified columns
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [127]:
#details about a data frame
#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)



# summary statistics
df_stats = df.describe()
print(df_stats)


(506, 2)
crim    float64
medv    float64
dtype: object
             crim        medv
count  506.000000  506.000000
mean     3.613524   22.532806
std      8.601545    9.197104
min      0.006320    5.000000
25%      0.082045   17.025000
50%      0.256510   21.200000
75%      3.677083   25.000000
max     88.976200   50.000000


In [131]:
#rename a column
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df=df.rename(columns = {'Type':'CarType'})

print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [132]:
#check for any null value
df.isnull().values.any()

True

In [133]:
#selecting as a dataframe instead of a series
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

End of Question one