In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


#write a function to read the data from the lab3.txt
# Reading the cube from a text file: Write a function to read the cube from a text file. The function
# should take a filename as input and return a 2D array representing the cube. The cube can be
# represented using a binary matrix, where 0 represents an empty cell and 1 represents a wall.

def read_cube(filename):
    with open(filename) as f:
        lines = f.readlines()
    cube = []
    for line in lines:
        cube.append([int(i) for i in line.split()])
    return np.array(cube)

# call the function to read the data from the lab3.txt
cube = read_cube('lab3.txt')
print(cube)



[[1 0 5 0 1 0 0]
 [1 1 0 0 0 1 1]
 [0 1 0 1 0 0 0]
 [1 1 0 1 1 0 1]
 [0 1 0 1 0 0 0]
 [0 1 1 1 0 1 1]
 [6 0 0 0 0 0 0]]


### Question 1

In [4]:
def DFS(cube):
    # get the dimension of the cube
    dim = cube.shape[0]
    # get the start point and the goal point
    start = np.where(cube == 5)
    goal = np.where(cube == 6)
    # create a stack to store the path
    stack = []
    # create a list to store the visited nodes
    visited = []
    # push the start point into the stack
    stack.append(start)
    # while the stack is not empty
    while stack:
        # pop the top element from the stack
        node = stack.pop()
        # if the node is not visited
        if node not in visited:
            # mark the node as visited
            visited.append(node)
            # if the node is the goal point
            if cube[node] == 6:
                # return the path
                return visited
            # get the neighbors of the node
            neighbors = get_neighbors(node, dim)
            # for each neighbor
            for neighbor in neighbors:
                # if the neighbor is not a wall
                if cube[neighbor] != 1:
                    # push the neighbor into the stack
                    stack.append(neighbor)
    
    # if there is no path from the start point to the goal point
    return -1

In [5]:
def BFS(cube):
    # get the dimension of the cube
    dim = cube.shape[0]
    # get the start point and the goal point
    start = np.where(cube == 5)
    goal = np.where(cube == 6)
    # create a queue to store the path
    queue = []
    # create a list to store the visited nodes
    visited = []
    # push the start point into the queue
    queue.append(start)
    # while the queue is not empty
    while queue:
        # pop the top element from the queue
        node = queue.pop(0)
        # if the node is not visited
        if node not in visited:
            # mark the node as visited
            visited.append(node)
            # if the node is the goal point
            if cube[node] == 6:
                # return the path
                return visited
            # get the neighbors of the node
            neighbors = get_neighbors(node, dim)
            # for each neighbor
            for neighbor in neighbors:
                # if the neighbor is not a wall
                if cube[neighbor] != 1:
                    # push the neighbor into the queue
                    queue.append(neighbor)
    
    # if there is no path from the start point to the goal point
    return -1


def get_neighbors(node, dim):
    neighbors = []
    # get the row and the column of the node
    row = node[0]
    col = node[1]
    # if the row is not the first row
    if row != 0:
        # add the node above the current node to the neighbors
        neighbors.append((row - 1, col))
    # if the row is not the last row
    if row != dim - 1:
        # add the node below the current node to the neighbors
        neighbors.append((row + 1, col))
    # if the column is not the first column
    if col != 0:
        # add the node to the left of the current node to the neighbors
        neighbors.append((row, col - 1))
    # if the column is not the last column
    if col != dim - 1:
        # add the node to the right of the current node to the neighbors
        neighbors.append((row, col + 1))
    return neighbors

In [6]:
#write a function that prints the path from the start point to the goal point
# it should print the path in the following format:
# 5 0 0 0 0 0 0
# 0 0 0 0 0 0 0
# 0 0 0 0 0 0 0
# 0 0 0 0 0 0 0
# 0 0 0 0 0 0 0
# 0 0 0 0 0 0 6
def print_path(path):
    # get the dimension of the cube
    dim = cube.shape[0]
    # create a copy of the cube
    cube_copy = np.copy(cube)
    # for each node in the path
    for node in path:
        # set the value of the node to 2
        cube_copy[node] = 9
    # print the cube
    print(cube_copy)
    

# call the DFS function to get the path from the start point to the goal point
path = DFS(cube)
# print the path
print_path(path)

[[1 0 9 9 1 0 0]
 [1 1 0 9 9 1 1]
 [0 1 0 1 9 9 9]
 [1 1 0 1 1 9 1]
 [0 1 0 1 9 9 9]
 [0 1 1 1 9 1 1]
 [9 9 9 9 9 9 9]]


In [7]:
# call the BFS function to get the path from the start point to the goal point
path2 = BFS(cube)
# print the path
print_path(path2)


[[1 9 9 9 1 0 0]
 [1 1 9 9 9 1 1]
 [0 1 9 1 9 9 9]
 [1 1 9 1 1 9 1]
 [0 1 9 1 9 9 9]
 [0 1 1 1 9 1 1]
 [9 9 9 9 9 9 9]]


In [8]:
# now write a function which uses the plotly to visualize the path
# the function should take the path as input and return a plotly figure
def visualize_path(path):
    # get the dimension of the cube
    dim = cube.shape[0]
    # create a copy of the cube
    cube_copy = np.copy(cube)
    # for each node in the path
    for node in path:
        # set the value of the node to 2
        cube_copy[node] = 9
    # create a dataframe from the cube
    df = pd.DataFrame(cube_copy)
    # create a plotly figure
    fig = px.imshow(df)
    # return the figure
    return fig

# call the function to visualize the path
fig = visualize_path(path)
# show the figure
fig.show()

# call the function to visualize the path
fig = visualize_path(path2)
# show the figure
fig.show()


### Question number 2

In [9]:
#write a function to read the cube from a text file
def read_cube(filename):
    # open the file
    with open(filename) as file:
        # read the lines
        lines = file.readlines()
        # create an empty list to store the lines
        lines_list = []
        # for each line
        for line in lines:
            # remove the new line character
            line = line.strip()
            # split the line
            line = line.split()
            # convert the line to a list of integers
            line = [int(i) for i in line]
            # append the line to the list
            lines_list.append(line)
        # convert the list to a numpy array
        cube = np.array(lines_list)
    # return the cube
    return cube

#call the function and read the cube
cube = read_cube('lab3q2.txt')
print(cube)

[[1 0 5 0 1 0 0]
 [1 1 0 0 0 1 1]
 [0 1 0 1 2 0 0]
 [1 1 2 1 1 2 1]
 [0 1 0 2 0 2 0]
 [0 1 1 1 0 1 1]
 [6 0 0 0 0 0 0]]


In [10]:
def A_star(cube):
    # get the dimension of the cube
    dim = cube.shape[0]
    # get the start point and the goal point
    start = np.where(cube == 5)
    goal = np.where(cube == 6)
    # create a queue to store the path
    queue = []
    # create a list to store the visited nodes
    visited = []
    # push the start point into the queue
    queue.append(start)
    # while the queue is not empty
    while queue:
        # pop the top element from the queue
        node = queue.pop(0)
        # if the node is not visited
        if node not in visited:
            # mark the node as visited
            visited.append(node)
            # if the node is the goal point
            if cube[node] == 6:
                # return the path
                return visited
            # get the neighbors of the node
            neighbors = get_neighbors(node, dim)
            # for each neighbor
            for neighbor in neighbors:
                # if the neighbor is not a wall
                if cube[neighbor] != 1:
                    # push the neighbor into the queue
                    queue.append(neighbor)
    
    # if there is no path from the start point to the goal point
    return -1


In [11]:
# write a fuction to print the path from the start point to the goal point
def print_path(path):
    # get the dimension of the cube
    dim = cube.shape[0]
    # create a copy of the cube
    cube_copy = np.copy(cube)
    # for each node in the path
    for node in path:
        # set the value of the node to 2
        cube_copy[node] = 9
    # print the cube
    print(cube_copy)
    
# call the A* function to get the path from the start point to the goal point
path2 = A_star(cube)
# print the path
print_path(path2)

[[1 9 9 9 1 0 0]
 [1 1 9 9 9 1 1]
 [0 1 9 1 9 9 9]
 [1 1 9 1 1 9 1]
 [0 1 9 9 9 9 9]
 [0 1 1 1 9 1 1]
 [9 9 9 9 9 9 9]]


In [12]:
# now plot the path using plotly
# call the function to visualize the path
fig = visualize_path(path2)
# show the figure
fig.show()

